Revert "Use margin height instead of border height in vertical alignment"
dompdf/dompdf pull request #2757
Opened 2022-01-21 16:13 UTC by Mellthas

This reverts commit 96a93459e06df326afee96a579f50d2594406237. It seems this was not an innocent fix as it seemed to be. Retain the existing behavior, which unfortunately undoes the small improvement to #1946.

Fixes #2756

2022-01-21 20:17 UTC, Spreeuw approved these changes
Fixes #2756 for me indeed! 🚀

2022-01-23 18:31 UTC, bsweeney requested changes
I don't think reverting this change is necessarily the way to go. I've noticed that alignment calculation is universally ... not great? I think the original logic just attempts to approximate the correct alignment without actually doing as the spec requires. Let's leave this open for now but I'm working on a change that I think will do a better job.

2022-01-23 19:40 UTC, Mellthas commented
Yeah, this would be the safe-route fix here, just not meddling with the logic for now.

But having looked at it again now, the top margin in #2756 seems to be a workaround for the misalignment really. The same can be achieved with `vertical-align: -10px` on the `ul` there, which works both with current master and with older versions. An advantage of the original change is that the difference in the baseline positions is now relatively stable no matter the margin, where it would differ greatly depending on the provided margin before. So the baselines are not correctly, but at least roughly, aligned. And any remaining misalignment can be worked around by using `vertical-align` with a specific length.

Let’s see what you have got :-); independently, it may be better to drop this PR, and consider the original change a small improvement instead.

2022-01-23 21:47 UTC, bsweeney commented
I agree, this does provide significant improvement generally despite the issue cited in 2756. Since there is a work-around I think we can drop this one. What I'm working on is a significant change to the logic so some review will definitely be in order. So far I'm pretty happy with the results.

2022-01-24 16:47 UTC, Mellthas commented
Alright then, let’s close this.

2022-01-24 16:47 UTC, closed without merging