test on PHP 8.2 + imagick + gmagick
dompdf/dompdf pull request #3074
Opened 2022-11-30 04:39 UTC by IonBazan

Adds PHP 8.2 to the build matrix and tests against `imagick` and `gmagick` extension.

I used `include` syntax so there is only one job for these extensions which should be enough.

2022-11-30 13:58 UTC, bsweeney requested changes
Can we test against variations in the extension configuration? Ideally we would run the test with and without the imagick extension.

2022-12-01 13:32 UTC, IonBazan commented
@bsweeney this is what's done now - we have PHP 7.1-8.2 with `gd` only, PHP 8.2 with `imagick` and PHP 8.1 with `gmagick`:
![image](https://user-images.githubusercontent.com/1985514/205065388-f7c7c337-d25c-40c1-ae8a-3f9475314142.png)


If you want, we can make it run in all combinations, but that would produce 20 CI jobs which I don't think is necessary as it's enough to check them with a single PHP version.

2022-12-01 13:56 UTC, bsweeney commented
Ah, sorry, my bad. Still getting my feet underneath me with regards to github actions. I meant to check myself on that an forgot.

2022-12-01 13:56 UTC, bsweeney approved these changes

2022-12-01 13:59 UTC, bsweeney commented
As far as checking against more versions I could go either way on that question, but it does seem excessive. Though eventually that may be the scenario we find ourselves in as more PHP versions are supported. Worth considering if we continually roll that check forward, maybe just use it on the last minor release (e.g., 7.4 and 8.2)?

2022-12-01 14:30 UTC, IonBazan commented
https://github.com/vitoc/gmagick seems a bit abandoned to me but let's keep it in the CI as this library still supports it. We can drop it after graceful deprecation and sunset cycle but it all depends on how many people use it with dompdf.

In the meantime, I think it's worth using this pipeline against #2510 to see if it still passes when Imagick is present (it did, when I run it locally).

2022-12-02 14:21 UTC, merged