Stylesheet parsing logic improvements
dompdf/dompdf pull request #3282
Opened 2023-09-24 13:54 UTC by bsweeney

- Updates regex patterns to improve stylesheet ingestion
- Improves media query handling
  - Supports media queries with more than one condition
  - Attaches all media queries to a single Style object instead of replicating the Style object for each query
  - Expands supports logical operators (not, or)
  - Fills out the media query logic for at-import rules
- Improves URI ("src" property) handling

2023-10-24 19:33 UTC, Mellthas requested changes

2023-10-25 14:17 UTC, bsweeney commented on src/Css/Stylesheet.php
> +                        $this->_parse_import($match["CSS_ATIMPORT_RULE"]);
I think you're right.

2023-10-25 14:19 UTC, bsweeney commented on src/Css/Stylesheet.php
> +                            $mq = [];
Good catch. I must not have tested with a sufficiently complex media query.

2023-10-25 14:42 UTC, bsweeney commented on src/Css/Stylesheet.php
> +                            $feature_match = $paper_height === (float)$style->length_in_pt($media_query_value);
How disappointingly sloppy of me.

2023-10-25 15:47 UTC, bsweeney commented
Thanks for reviewing this. I definitely need a co-pilot next to me 😅

2023-10-26 00:26 UTC, Mellthas approved these changes
Looks like a nice set of improvements!

2023-10-26 00:39 UTC, merged